-- migrate:up

ALTER TABLE Users ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ChatRooms ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Messages ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- migrate:down

ALTER TABLE Users DROP COLUMN createdAt;
ALTER TABLE ChatRooms DROP COLUMN createdAt;
ALTER TABLE Messages DROP COLUMN createdAt;
