-- migrate:up
ALTER TABLE Users 
ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN deletedAt TIMESTAMP NULL;

ALTER TABLE ChatRooms
ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN deletedAt TIMESTAMP NULL;

ALTER TABLE Messages
ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN deletedAt TIMESTAMP NULL;

-- migrate:down
ALTER TABLE Users 
DROP COLUMN updatedAt,
DROP COLUMN deletedAt;

ALTER TABLE Chatrooms 
DROP COLUMN updatedAt,
DROP COLUMN deletedAt;

ALTER TABLE Messages 
DROP COLUMN updatedAt,
DROP COLUMN deletedAt;

